name: Page

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Generate your content
        run: npm run build

      - name: Inject Custom Domain
        run: echo "cheatsheet.iotafox.com" > build/CNAME 

      - name: Publish current workdir (which contains generated content) to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.3

        with:
          source-directory: build
          target-branch: gh-pages
